### PR TITLE
Fix namespace behavior

### LINKED ISSUE #87: Creating SMBShares in different namespaces
Looking at the code, the operator creates the resources (PVC, Deployment, Service) in the operator's namespace and then sets the SMBShare resource as the owner of these resources (to have K8S garbage collect them).  

But, K8S does not allow cross namespace ownership. So, if the SMBShare is created in a different namespace, this operation will fail. Please note that the return value is not checked: https://github.com/samba-in-kubernetes/samba-operator/blob/878ac25673c0fd7d3a2f2294f8714843c6179c86/internal/resources/smbshare.go#L311

In the demo showed in SambaXP right after provisioning the operator the context is set to use the namespace of the operator. As a result, all the resources created in the demo are created in that namespace and this issue does not occur.

Is the intention to force the users to create SMBShares only in the operator's namespace?

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Fixes #87

These changes reverse the well intentioned but incorrect attempt at managing all created resources under the namespace the operator runs in. It restores the previous behavior such that deployments/pods/services/etc will be created in the namespace that the SmbShare resource "owning" those resources is placed in.

This also fixes up the existing "other namespace" test to conform to the new behavior.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
found a bug by re reading my code. moving to draft.

File: internal/resources/smbshare.go [hunk 1]
```diff
@@ -191,7 +191,8 @@ func (m *SmbShareManager) Finalize(
 	ctx context.Context,
 	instance *sambaoperatorv1alpha1.SmbShare) Result {
 	// ---
-	cm, err := getConfigMap(ctx, m.client, m.cfg.WorkingNamespace)
+	destNamespace := instance.Namespace
```
Comment (raghavendra-talur) [inline internal/resources/smbshare.go:194]: IMO, it would be easier to read if you used instance.Namespace as an argument in the next line.

**Review by raghavendra-talur — APPROVED** [review]

File: internal/resources/smbshare.go (hunk 1 above)
Comment (phlogistonjohn) [reply internal/resources/smbshare.go:194]: It's there to help me remember things better. I'll think I will leave it for now, thanks.

**Review by raghavendra-talur — APPROVED** [review]
